# Generated by Django 3.2.5 on 2022-03-29 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='productcolor',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='img',
            new_name='image',
        ),
    ]
