# Generated by Django 4.0.3 on 2022-04-03 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_stock_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='images/product-color/'),
        ),
    ]
