# Generated by Django 4.0.3 on 2022-04-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='image',
            field=models.FileField(default=None, upload_to='images/sub-category/'),
        ),
    ]
