# Generated by Django 4.0.3 on 2022-04-05 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_subcategory_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default=None, upload_to='images/category/'),
        ),
        migrations.AlterField(
            model_name='headerbanner',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/header/'),
        ),
        migrations.AlterField(
            model_name='offers',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/offers/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images/product/'),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/product-color/'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/product/'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='image',
            field=models.ImageField(default=None, upload_to='images/sub-category/'),
        ),
    ]
