# Generated by Django 4.0.3 on 2022-04-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_category_image_alter_headerbanner_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video_url',
        ),
        migrations.AddField(
            model_name='product',
            name='youtube_video_url',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='brand',
            name='link',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
