# Generated by Django 4.0.3 on 2022-04-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_remove_contact_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=250)),
                ('answer', models.TextField()),
            ],
        ),
    ]
