# Generated by Django 4.0.3 on 2022-04-05 14:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='contact_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
