# Generated by Django 4.0.3 on 2022-04-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_contact_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
