# Generated by Django 4.0.3 on 2022-04-04 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_check_out'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingCharges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('charges', models.IntegerField()),
            ],
        ),
    ]
